# Based on https://github.com/tommilligan/mdbook-admonish/blob/main/.github/workflows/deploy.yml

name: Release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write # for publishing release
    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release --target x86_64-unknown-linux-musl

      - run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "CRATE_NAME=$(basename $PWD)" >> $GITHUB_ENV

      - run: |
          mkdir target/stage
          cd target/x86_64-unknown-linux-musl/release
          tar czvf ../../stage/${{ env.CRATE_NAME }}-${{ env.RELEASE_VERSION }}.tar.gz ${{ env.CRATE_NAME }}

      - name: Upload the binary releases
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/stage/*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          release_name: v${{ env.RELEASE_VERSION }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  publish-crates-io:
    name: Publish on crates.io
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Publish
        run: cargo publish --locked --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
